name: Build and Deploy to GitHub Pages

# This workflow runs whenever you push a change to your 'main' branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a standard virtual machine
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      # Step 2: Build your Angular application
      - name: Build ğŸ”§
        run: |
          npm install
          ng build --base-href /greeter-ui/

      # Step 3: Deploy the correct folder to the 'gh-pages' branch
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch to deploy to
          folder: dist/greeter-ui # The folder to deploy from